<?php
// Custom WP Admin functions
if ( ! defined( 'ABSPATH' ) ) { exit; }

// Custom WP Login logo
add_action( 'login_enqueue_scripts', 'custom_jw_login_logo' );
function custom_jw_login_logo() {
  $default_logo = get_stylesheet_directory_uri() . '/images/favicon.png';
  $site_logo = get_theme_mod('custom_logo');
  $custom_logo = !empty($site_logo) ? wp_get_attachment_image_src($site_logo, 'login-logo') : $default_logo;
  echo '<style type="text/css">
  #login h1 a, .login h1 a {background-image: url('. $custom_logo[0] .');height: 100px;width: 320px;background-repeat: no-repeat;background-size: auto;background-position: center;}
  </style>';
}

add_filter( 'login_headerurl', 'custom_jw_login_logo_url' );
function custom_jw_login_logo_url() {
  return home_url();
}

add_filter( 'login_headertitle', 'custom_jw_login_logo_title' );
function custom_jw_login_logo_title() {
  return get_bloginfo('name');
}

// Disable Wordpress admin dashboard boxes generated by theme or plugin via customizer settings
$disable_wpdashboard_box = get_theme_mod( 'htc_dashboard_cleanup_setting' );
$disable_wpdashboard_box_default = true;

if( "no" == $disable_wpdashboard_box ){
  $disable_wpdashboard_box_default = false;
  remove_action( 'wp_dashboard_setup', 'custom_jw_disable_db_widgets' );
}

if( true == $disable_wpdashboard_box_default ){
	add_action( 'wp_dashboard_setup', 'custom_jw_disable_db_widgets', 999 );	
}

function custom_jw_disable_db_widgets() {
   // Welcome panel
  remove_action( 'welcome_panel', 'wp_welcome_panel' );
  // Gutenberg box
  remove_action( 'try_gutenberg_panel', 'wp_try_gutenberg_panel' );
  global $wp_meta_boxes;
  // Activity
  unset( $wp_meta_boxes['dashboard']['normal']['core']['dashboard_activity'] );
  // At a Glance
  unset( $wp_meta_boxes['dashboard']['normal']['core']['dashboard_right_now'] );
  // Recent comments
  unset( $wp_meta_boxes['dashboard']['normal']['core']['dashboard_recent_comments'] );
  // Links
  unset( $wp_meta_boxes['dashboard']['normal']['core']['dashboard_incoming_links'] );
  // Plugins
  unset( $wp_meta_boxes['dashboard']['normal']['core']['dashboard_plugins'] );
  // Wordfence
  unset( $wp_meta_boxes['dashboard']['normal']['core']['wordfence_activity_report_widget'] );
  // WPMUdev
  unset( $wp_meta_boxes['dashboard']['normal']['core']['wpmudev_widget'] );
  unset( $wp_meta_boxes['dashboard']['normal']['core']['wpmudev_news_widget'] );
  // Elementor Overview
  unset( $wp_meta_boxes['dashboard']['normal']['core']['e-dashboard-overview'] );
  unset( $wp_meta_boxes['dashboard']['side']['core']['e-dashboard-overview'] );
  // bbpress
  unset( $wp_meta_boxes['dashboard']['normal']['core']['bbp-dashboard-right-now'] );
  // Yoast seo
  unset( $wp_meta_boxes['dashboard']['normal']['core']['yoast_db_widget'] );
  // Gravity Forms
  // unset( $wp_meta_boxes['dashboard']['normal']['core']['rg_forms_dashboard'] );
  unset( $wp_meta_boxes['dashboard']['side']['core']['dashboard_primary'] );
  unset( $wp_meta_boxes['dashboard']['side']['core']['dashboard_secondary'] );
  // Quick draft
  unset( $wp_meta_boxes['dashboard']['side']['core']['dashboard_quick_press'] );
  // Recent drafts
  unset( $wp_meta_boxes['dashboard']['side']['core']['dashboard_recent_drafts'] );
}

// Remove admin bar menu items
add_action( 'admin_bar_menu', 'custom_jw_remove_admin_menu_items', 999 );
function custom_jw_remove_admin_menu_items( $wp_admin_bar ) {
  $wp_admin_bar->remove_node( 'wp-logo' );
  $wp_admin_bar->remove_node( 'updates' );
  $wp_admin_bar->remove_node( 'comments' );
  $getgreetings = $wp_admin_bar->get_node('my-account');
  $rpctitle = str_replace('Howdy,','',$getgreetings->title);
  $wp_admin_bar->add_node(array("id"=>"my-account","title"=>$rpctitle));
}

// Admin page css
add_action( 'admin_head', 'custom_jw_admin_head_css' );
function custom_jw_admin_head_css(){
  echo '<style type="text/css">
  #pageparentdiv label.post-attributes-label[for="page_template"], #pageparentdiv label.post-attributes-label[for="menu_order"], #pageparentdiv select#page_template,  #pageparentdiv #menu_order {display: none;}
  </style>';
}

// Remove thumbnail attr in page type
add_action( 'init', 'custom_jw_remove_posttype_support' );
function custom_jw_remove_posttype_support() {
    remove_post_type_support( 'page', 'thumbnail' );
}

// Admin footer text modification
add_filter( 'admin_footer_text', 'custom_jw_footer_text_admin' );
function custom_jw_footer_text_admin () {
  echo '<span id="footer-thankyou">Jtheme Jello by <a href="https://www.jezweb.com.au" target="_blank">Jezweb</a></span>';
}

// Enable svg file upload
add_filter( 'upload_mimes', 'custom_jw_svg_file_upload' );
function custom_jw_svg_file_upload($mimes) {
  $mimes['svg'] = 'image/svg+xml';
  $mimes['webp'] = 'image/webp';
  return $mimes;
}

// Enable shortcodes in text widgets
add_filter( 'widget_text', 'do_shortcode' );

// Attachment page redirect
add_action( 'template_redirect', 'custom_hello_theme_attachment_redirect', 1 );
function custom_hello_theme_attachment_redirect() {
  global $post;
  if ( is_attachment() && isset($post->post_parent) && is_numeric($post->post_parent) && ($post->post_parent != 0) ) {
    wp_redirect(get_permalink($post->post_parent), 301); // permanent redirect to post/page where image or document was uploaded
    exit;
  } elseif ( is_attachment() && isset($post->post_parent) && is_numeric($post->post_parent) && ($post->post_parent < 1) ) { // for some reason it doesnt works checking for 0, so checking lower than 1 instead...
    wp_redirect(get_bloginfo('wpurl'), 302); // temp redirect to home for image or document not associated to any post/page
    exit;
  }
}

// Disable comments functionality via customizer settings
$disable_comments = get_theme_mod( 'htc_comments_setting' );
$disable_comments_default = true;

if( "no" == $disable_comments ){
  $disable_comments_default = false;
}

if( true == $disable_comments_default ){
  include( 'custom_disable_comments.php' );
}