name: 'Build Theme (Release)'
description: 'Build Hello Elementor theme with specified version using Hello Commerce approach'

inputs:
  PACKAGE_VERSION:
    description: 'The package version to build (e.g. 3.4.4)'
    required: true
  BUILD_SCRIPT_PATH:
    description: 'Path to build script'
    required: false
    default: "npm run package:zip"

runs:
  using: "composite"
  steps:
    - name: Install npm dependencies
      shell: bash
      run: |
        export PUPPETEER_SKIP_DOWNLOAD=true
        export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
        npm ci

    - name: Install composer dependencies
      shell: bash
      run: |
        composer install --no-dev --no-scripts --optimize-autoloader

    - name: Set package version
      shell: bash
      env:
        PACKAGE_VERSION: ${{ inputs.PACKAGE_VERSION }}
      run: |
        echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
        echo "Building Hello Elementor theme version: ${PACKAGE_VERSION}"

    - name: Build theme
      shell: bash
      run: |
        if [[ "${{ inputs.BUILD_SCRIPT_PATH }}" == npm* ]]; then
          ${{ inputs.BUILD_SCRIPT_PATH }}
        else
          bash "${{ inputs.BUILD_SCRIPT_PATH }}"
        fi

    - name: Set build directory and zip paths
      shell: bash
      env:
        PACKAGE_VERSION: ${{ inputs.PACKAGE_VERSION }}
      run: |
        set -e
        THEME_NAME=$(node -p "require('./package.json').name")
        BUILD_DIR="${THEME_NAME}"
        BUILD_ZIP_PATH="${THEME_NAME}.${PACKAGE_VERSION}.zip"
        
        echo "Setting build paths:"
        echo "  THEME_NAME: ${THEME_NAME}"
        echo "  BUILD_DIR: ${BUILD_DIR}"
        echo "  BUILD_ZIP_PATH: ${BUILD_ZIP_PATH}"
        echo "  PACKAGE_VERSION: ${PACKAGE_VERSION}"
        
        if [ ! -d "$BUILD_DIR" ]; then
          echo "❌ Build directory not found: $BUILD_DIR"
          echo "Available directories:"
          ls -la | head -20
          exit 1
        fi
        
        echo "✅ Build directory found: $BUILD_DIR"
        echo "✅ Zip file: $BUILD_ZIP_PATH"
        
        echo "BUILD_DIR=${BUILD_DIR}" >> $GITHUB_ENV
        echo "BUILD_ZIP_PATH=${BUILD_ZIP_PATH}" >> $GITHUB_ENV
        
        echo "✅ Environment variables set in GITHUB_ENV"
