name: 'Theme Slack Notification (Release)'
description: 'Send Slack notification for Hello Elementor release'
inputs:
  CLOUD_SLACK_BOT_TOKEN:
    required: true
    description: 'Slack bot token'
  PACKAGE_VERSION:
    required: true
    description: 'Release version'
  SLACK_CHANNEL:
    required: false
    default: '#tmz-hello-delivery'
    description: 'Slack channel to send notification to'

runs:
  using: 'composite'
  steps:
    - name: Post to Slack
      shell: bash
      env:
        CLOUD_SLACK_BOT_TOKEN: ${{ inputs.CLOUD_SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: ${{ inputs.SLACK_CHANNEL }}
        PACKAGE_VERSION: ${{ inputs.PACKAGE_VERSION }}
      run: |
        node << 'NODE_SCRIPT'
        const slackChannel = process.env.SLACK_CHANNEL || '#tmz-hello-delivery';
        const packageVersion = process.env.PACKAGE_VERSION || '';
        
        const payload = {
          text: `Hello Elementor v${packageVersion} Released!`,
          blocks: [
            {
              type: 'header',
              text: {
                type: 'plain_text',
                text: `Hello Elementor v${packageVersion} Released!`
              }
            },
            {
              type: 'section',
              text: {
                type: 'mrkdwn',
                text: '*Hello Elementor theme* has been successfully released and is ready for distribution.'
              }
            },
            {
              type: 'section',
              fields: [
                {
                  type: 'mrkdwn',
                  text: `*Version:*\nv${packageVersion}`
                }
              ]
            }
          ]
        };
        
        process.env.SLACK_PAYLOAD = JSON.stringify(payload);
        
        const { execSync } = require('child_process');
        const path = require('path');
        const scriptPath = path.join(process.env.GITHUB_WORKSPACE, '.github/scripts/send-slack-message.js');
        execSync(`node "${scriptPath}"`, { stdio: 'inherit', env: process.env });
        NODE_SCRIPT

    - name: Notification summary
      shell: bash
      run: |
        echo "📢 Slack notification sent!"
        echo "   - Channel: ${{ inputs.SLACK_CHANNEL }}"
        echo "   - Version: v${{ inputs.PACKAGE_VERSION }}"
