name: 'Theme Slack Notification (Release)'
description: 'Send Slack notification for Hello Elementor release'
inputs:
  SLACK_BOT_TOKEN:
    required: true
    description: 'Slack bot token'
  PACKAGE_VERSION:
    required: true
    description: 'Release version'
  BUILD_ZIP_PATH:
    required: true
    description: 'Path to theme zip file'
  GITHUB_RELEASE_URL:
    required: true
    description: 'GitHub release URL'
  SLACK_CHANNEL:
    required: false
    default: '#general'
    description: 'Slack channel to send notification to'
  WPORG_DEPLOYMENT_STATUS:
    required: false
    default: 'skipped'
    description: 'WordPress.org deployment status (deployed|skipped|disabled)'

runs:
  using: 'composite'
  steps:
    - name: Prepare deployment message
      id: deployment-message
      shell: bash
      run: |
        case "${{ inputs.WPORG_DEPLOYMENT_STATUS }}" in
          "deployed")
            MESSAGE="📦 *WordPress.org Deployment*\\n• ✅ Automatically deployed to WordPress.org\\n• Theme available at: https://wordpress.org/themes/hello-elementor/\\n• No manual upload required! 🎉"
            ;;
          "disabled")
            MESSAGE="📦 *WordPress.org Deployment*\\n• ⚠️ Disabled in configuration\\n• Manual upload required to WordPress.org\\n• Download zip from GitHub release below"
            ;;
          *)
            MESSAGE="📦 *WordPress.org Deployment*\\n• ⚠️ Skipped (deploy_to_wporg: false)\\n• Manual upload required to WordPress.org\\n• Download zip from GitHub release below"
            ;;
        esac
        echo "DEPLOYMENT_MESSAGE=$MESSAGE" >> $GITHUB_ENV
    
    - name: Get file info
      id: file-info
      shell: bash
      run: |
        if [ -f "${{ inputs.BUILD_ZIP_PATH }}" ]; then
          FILE_SIZE=$(stat -c%s "${{ inputs.BUILD_ZIP_PATH }}" 2>/dev/null || stat -f%z "${{ inputs.BUILD_ZIP_PATH }}")
          FILE_SIZE_MB=$(echo "scale=2; $FILE_SIZE / 1024 / 1024" | bc -l 2>/dev/null || echo "$((FILE_SIZE / 1024 / 1024)).0")
          echo "FILE_SIZE=$FILE_SIZE" >> $GITHUB_ENV
          echo "FILE_SIZE_MB=${FILE_SIZE_MB}MB" >> $GITHUB_ENV
        else
          echo "FILE_SIZE_MB=Unknown" >> $GITHUB_ENV
        fi

    - name: Post to Slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: ${{ inputs.SLACK_CHANNEL }}
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "🚀 Hello Elementor v${{ inputs.PACKAGE_VERSION }} Released!"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Hello Elementor theme* has been successfully released and is ready for distribution."
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Version:*\nv${{ inputs.PACKAGE_VERSION }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Package Size:*\n${{ env.FILE_SIZE_MB }}"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ env.DEPLOYMENT_MESSAGE }}"
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "📥 Download Release"
                    },
                    "url": "${{ inputs.GITHUB_RELEASE_URL }}",
                    "style": "primary"
                  }
                ]
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "Build: ${{ inputs.BUILD_ZIP_PATH }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}

    - name: Notification summary
      shell: bash
      run: |
        echo "📢 Slack notification sent!"
        echo "   - Channel: ${{ inputs.SLACK_CHANNEL }}"
        echo "   - Version: v${{ inputs.PACKAGE_VERSION }}"
        echo "   - Release: ${{ inputs.GITHUB_RELEASE_URL }}"
        case "${{ inputs.WPORG_DEPLOYMENT_STATUS }}" in
          "deployed")
            echo "   - WordPress.org: ✅ Automatically deployed"
            ;;
          "disabled")
            echo "   - WordPress.org: ⚠️ Disabled in configuration"
            ;;
          *)
            echo "   - WordPress.org: ⚠️ Skipped (deploy_to_wporg: false)"
            ;;
        esac
