<?php

namespace Hello420Theme\Includes;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

/**
 * Lightweight script loader (no build step required).
 *
 * If a ".asset.php" file exists (generated by @wordpress/scripts), it will be used.
 * Otherwise the script is enqueued directly from /assets/js.
 */
class Script {
	protected string $handle;
	protected array $dependencies;
	protected array $localize;

	public function __construct( string $handle, array $dependencies = [], array $localize = [] ) {
		$this->handle       = $handle;
		$this->dependencies = $dependencies;
		$this->localize     = $localize;
	}

	public function enqueue(): void {
		$script_path = HELLO420_SCRIPTS_PATH . $this->handle . '.js';
		$script_url  = HELLO420_SCRIPTS_URL . $this->handle . '.js';

		// Fail-safe: do not fatal if a script handle is referenced but the file is missing.
		if ( ! file_exists( $script_path ) ) {
			return;
		}

		$asset_path = HELLO420_SCRIPTS_PATH . $this->handle . '.asset.php';
		$asset      = [
			'dependencies' => [],
			'version'      => HELLO420_VERSION,
		];

		if ( file_exists( $asset_path ) ) {
			$loaded = require $asset_path;
			if ( is_array( $loaded ) ) {
				$asset['dependencies'] = isset( $loaded['dependencies'] ) && is_array( $loaded['dependencies'] ) ? $loaded['dependencies'] : [];
				$asset['version']      = isset( $loaded['version'] ) ? (string) $loaded['version'] : HELLO420_VERSION;
			}
		} else {
			$asset['version'] = (string) filemtime( $script_path );
		}

		$deps = array_values( array_unique( array_merge( $asset['dependencies'], $this->dependencies ) ) );

		wp_enqueue_script(
			$this->handle,
			$script_url,
			$deps,
			$asset['version'],
			true
		);

		// i18n for theme scripts (safe no-op if translation files are not present).
		if ( function_exists( 'wp_set_script_translations' ) ) {
			wp_set_script_translations( $this->handle, HELLO420_TEXT_DOMAIN );
		}

		$this->enqueue_inline_bootstrap();
	}

	private function enqueue_inline_bootstrap(): void {
		static $bootstrapped = false;

		$base = [
			'version'  => HELLO420_VERSION,
			'slug'     => HELLO420_THEME_SLUG,
			'themeUrl' => get_template_directory_uri(),
			'adminUrl' => admin_url(),
			'restUrl'  => esc_url_raw( rest_url() ),
			'nonce'    => wp_create_nonce( 'wp_rest' ),
		];

		$data = array_merge( $base, $this->localize );

		$js = 'window.HELLO420 = window.HELLO420 || ' . wp_json_encode( $data ) . ';';

		// Configure wp.apiFetch (if loaded) with nonce + root URL.
		if ( ! $bootstrapped ) {
			$js .= "\n" . '(function(){ if(!window.wp||!wp.apiFetch){return;}'
				. 'try{ if(wp.apiFetch.createNonceMiddleware){wp.apiFetch.use(wp.apiFetch.createNonceMiddleware(window.HELLO420.nonce));} }catch(e){}'
				. 'try{ if(wp.apiFetch.createRootURLMiddleware){wp.apiFetch.use(wp.apiFetch.createRootURLMiddleware(window.HELLO420.restUrl));} }catch(e){}'
				. '})();';
			$bootstrapped = true;
		}

		wp_add_inline_script( $this->handle, $js, 'before' );
	}
}
